packages:
  - "packages/*"
  - "!packages/test-app"

catalog:
  "@biomejs/biome": "^1.9.4"
  "@changesets/cli": "^2.28.1"
  "@rollup/plugin-commonjs": "^28.0.2"
  "@rollup/plugin-json": "^6.1.0"
  "@rollup/plugin-typescript": "^12.1.2"
  "@types/node": "^22.13.9"
  "husky": "^9.1.7"
  "npm-check-updates": "^17.1.15"
  "rollup": "^4.34.9"
  "rollup-plugin-copy": "^3.5.0"
  "rollup-plugin-dts": "^6.1.1"
  "tslib": "^2.8.1"
  "typescript": "^5.8.2"
  "vite-tsconfig-paths": "^5.1.4"
  "vitest": "^3.0.7"
  "tsx": "4.19.3"
