name: Release and Publish

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      - name: Install Dependencies
        run: |
          corepack enable
          pnpm install --frozen-lockfile

      - name: Run Unit Tests
        run: pnpm run test:ci

      - name: Run Build Tests
        run: pnpm run test:build

  release:
    name: Versioning & Release
    runs-on: ubuntu-latest
    needs: test  # Ensures tests pass before running
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      - name: Install Dependencies
        run: |
          corepack enable
          pnpm install --frozen-lockfile

      - name: Create a Version & Changelog (if needed)
        run: pnpm changeset version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get New Version
        id: version
        run: echo "new_version=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Ensure CHANGELOG Exists
        run: touch CHANGELOG.md

      - name: Commit and Push Version Bump
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git diff --quiet && echo "No changes to commit" || (git add . && git commit -m "🔖 v${{ env.new_version }} [skip ci]" && git push)

  publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    needs: release  # Runs only if versioning is successful
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org/"

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      - name: Install Dependencies
        run: |
          corepack enable
          pnpm install --frozen-lockfile

      - name: Build Library
        run: pnpm run build

      - name: Publish to npm
        run: pnpm publish dist --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.new_version }}
          name: Release v${{ env.new_version }}
          body_path: ./CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

