name: ✅ Test Build

on:
  workflow_dispatch:
    inputs:
      trigger:

jobs:
  test-build:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: 🔄 Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }} # Checkout the PR branch

      - name: 🔧 Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: 📦 Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: 📂 Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: ⚡ Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: 📥 Install dependencies
        run: pnpm install --filter=@cano-ts/core

      - name: ✅ Run tests build
        run: pnpm run test:build
